version: '3.8'

services:
 fastapi:
    build: .
    command: python main.py
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db

 db:
    image: postgres:latest
    environment:
      POSTGRES_DB: menus
      POSTGRES_USER: restaurant_admin
      POSTGRES_PASSWORD: restaurant_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data:
