version: '3.8'

services:
 db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: DishDB
      POSTGRES_DB: cafe_db
      POSTGRES_INITDB_ARGS: "-c client_min_messages=warning"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
 app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db